from tools.example import TOOLS as _BASE_TOOLS, HANDLERS as _BASE_HANDLERS
from tools.vendoratlas import TOOLS as _VA_TOOLS, HANDLERS as _VA_HANDLERS

ALL_TOOLS = _BASE_TOOLS + _VA_TOOLS
ALL_HANDLERS = {**_BASE_HANDLERS, **_VA_HANDLERS}
